# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/settings_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChildWindow(object):
    def setupUi(self, ChildWindow):
        ChildWindow.setObjectName("ChildWindow")
        ChildWindow.resize(417, 320)
        ChildWindow.setStyleSheet("background-color: #191919;\n"
"")
        self.centralwidget = QtWidgets.QWidget(ChildWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(417, 320))
        self.centralwidget.setMaximumSize(QtCore.QSize(417, 320))
        self.centralwidget.setObjectName("centralwidget")
        self.le_input_ip = QtWidgets.QLineEdit(self.centralwidget)
        self.le_input_ip.setGeometry(QtCore.QRect(130, 80, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.le_input_ip.setFont(font)
        self.le_input_ip.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.le_input_ip.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"color: white;\n"
"border: none;\n"
"outline: none;\n"
"")
        self.le_input_ip.setObjectName("le_input_ip")
        self.le_input_port = QtWidgets.QLineEdit(self.centralwidget)
        self.le_input_port.setGeometry(QtCore.QRect(130, 160, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.le_input_port.setFont(font)
        self.le_input_port.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.le_input_port.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"color: white;\n"
"border: none;\n"
"outline: none;\n"
"")
        self.le_input_port.setObjectName("le_input_port")
        self.lbl_ip = QtWidgets.QLabel(self.centralwidget)
        self.lbl_ip.setGeometry(QtCore.QRect(20, 80, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.lbl_ip.setFont(font)
        self.lbl_ip.setStyleSheet("color: white;\n"
"border: 1px solid #e6b333;")
        self.lbl_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ip.setObjectName("lbl_ip")
        self.lbl_port = QtWidgets.QLabel(self.centralwidget)
        self.lbl_port.setGeometry(QtCore.QRect(20, 160, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.lbl_port.setFont(font)
        self.lbl_port.setStyleSheet("color: white;\n"
"border: 1px solid #e6b333;")
        self.lbl_port.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_port.setObjectName("lbl_port")
        self.btn_connect_to_server = QtWidgets.QPushButton(self.centralwidget)
        self.btn_connect_to_server.setGeometry(QtCore.QRect(20, 240, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.btn_connect_to_server.setFont(font)
        self.btn_connect_to_server.setStyleSheet("color: white;\n"
"background-color: #e6b333;")
        self.btn_connect_to_server.setObjectName("btn_connect_to_server")
        self.lbl_settings = QtWidgets.QLabel(self.centralwidget)
        self.lbl_settings.setGeometry(QtCore.QRect(20, 20, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.lbl_settings.setFont(font)
        self.lbl_settings.setStyleSheet("color: white;\n"
"border: 1px solid #e6b333;")
        self.lbl_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_settings.setObjectName("lbl_settings")
        ChildWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChildWindow)
        QtCore.QMetaObject.connectSlotsByName(ChildWindow)

    def retranslateUi(self, ChildWindow):
        _translate = QtCore.QCoreApplication.translate
        ChildWindow.setWindowTitle(_translate("ChildWindow", "MainWindow"))
        self.lbl_ip.setText(_translate("ChildWindow", "IP"))
        self.lbl_port.setText(_translate("ChildWindow", "PORT"))
        self.btn_connect_to_server.setText(_translate("ChildWindow", "Присоединиться к серверу"))
        self.lbl_settings.setText(_translate("ChildWindow", "Настройки"))
